const express = require("express");
const router = express.Router();
const Record = require("../models/Record");
const auth = require("../middleware/auth");

// GET /api/export/:id - Generates a downloadable "Receipt" or "Statement"
router.get("/:id", auth, async (req, res) => {
  try {
    const record = await Record.findById(req.params.id);
    if (!record) return res.status(404).json({ error: "Record not found" });

    // --- SECURITY CHECK (Same as your original) ---
    const isOwner = record.createdBy.toString() === req.user._id.toString();
    const isAdmin = req.user.role?.name === "admin";

    if (!isOwner && !isAdmin) {
      return res
        .status(403)
        .json({ error: "Unauthorized access to this statement" });
    }

    // Instead of streaming MP4 chunks, we generate a text-based "Statement"
    const statementContent = `
      ZORVYN FINANCE - TRANSACTION STATEMENT
      --------------------------------------
      ID: ${record._id}
      Date: ${record.createdAt}
      Description: ${record.description}
      Category: ${record.category}
      Type: ${record.type.toUpperCase()}
      Amount: $${record.amount.toFixed(2)}
      Status: ${record.status.toUpperCase()}
      --------------------------------------
      Generated by Zorvyn Analytics Engine
    `;

    // Set headers to trigger a file download in the browser
    res.setHeader("Content-Type", "text/plain");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=statement-${record._id}.txt`,
    );

    // Send the data
    res.send(statementContent);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
